version: 2.1

jobs:

  deploy:
    docker:
      # AWS CLI の入った Docker イメージ
      - image: xueshanf/awscli
        environment:
          # アップロード先の S3 バケット名
          BUCKET_NAME: XXX
          # アップロードしたいディレクトリ
          ROOT_DIR: public
    working_directory: ~/app
    steps:
      - checkout
      - deploy:
          name: "Upload S3"
          # AWS CLI で S3 にファイルをアップロードするコマンド
          command: |
            aws s3 sync --exact-timestamps --cache-control "no-cache" --exclude "**/.*" --delete $ROOT_DIR s3://$BUCKET_NAME

workflows:
  version: 2

  # ワークフロー名
  deploy:
    # 実行するジョブ一覧
    jobs:
      - deploy:
          filters:
            # master ブランチのみで実行する
            branches:
              only:
                - master
